import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { DateTime } from 'luxon';
import prisma from '@/lib/prisma';

export const metadata: Metadata = {
  title: 'DETL Blog | Post',
  description: 'Generated by Next.js',
};

type Props = {
  params: { slug: string };
};

export default async function Single({ params }: Props) {
  const post = await prisma.post.findUnique({
    where: {
      slug: params.slug,
      published: true,
      author: { email: 'bbcparfait@example.com' },
    },
    include: { author: true },
  });

  if (!post) {
    notFound();
  }

  return (
    <main>
      <div className='max-w-[1200px] mx-auto py-10 px-4'>
        <h1 className='text-4xl font-semibold  mb-4'>{post.title}</h1>
        <p className='mb-4'>
          By{' '}
          <span className='font-semibold'>
            {post.author.email} |{' '}
            {DateTime.fromISO(post.createdAt.toISOString()).toRelative()}
          </span>
        </p>
        <p className='leading-8'>{post.content}</p>
      </div>
    </main>
  );
}
