import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'DETL Blog | Demo',
  description: 'Generated by Next.js',
};

export default async function Demo() {
  return (
    <main>
      <div className='max-w-[1200px] mx-auto py-10 px-4'>
        <h1 className='text-4xl font-semibold mb-4'>
          React <q>useActionState</q> Demo
        </h1>
        <p className='leading-8'>This is a demo of the useActionState hook.</p>
      </div>
    </main>
  );
}
