import { Metadata } from 'next';

import { CreatePostForm } from '@/components/custom/create-form';

export const metadata: Metadata = {
  title: 'DETL Blog | Create a post',
  description: 'Generated by Next.js',
};

export default async function CreatePost() {
  return (
    <main>
      <div className='max-w-[1200px] mx-auto py-10 px-4'>
        <h1 className='text-4xl font-semibold mb-4'>Create a post</h1>

        <p className='leading-8'>Fill out the form below to create a post.</p>

        <CreatePostForm />
      </div>
    </main>
  );
}
