import { Metadata } from 'next';
import { Fredoka } from 'next/font/google';

import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { Container } from '@/components/layout/container';
import { Toaster } from '@/components/ui/toaster';

import '@/styles/global.css';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const sansFont = Fredoka({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${sansFont.className} text-xl text-slate-800`}>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
        <Toaster />
      </body>
    </html>
  );
}
