import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'DETL Blog | Home',
  description: 'Generated by Next.js',
};

export default async function Home() {
  return (
    <main>
      <div className='max-w-[1200px] mx-auto py-10 px-4'>
        <h1 className='text-4xl font-semibold mb-4'>
          Welcome to the DETL Blog!
        </h1>
        <p className='leading-8'>
          This site is meant for development purposes only.
        </p>
      </div>
    </main>
  );
}
