import Link from 'next/link';
import { Metadata } from 'next';
import { DateTime } from 'luxon';
import prisma from '@/lib/prisma';

export const metadata: Metadata = {
  title: 'DETL Blog | Home',
  description: 'Generated by Next.js',
};

export default async function Home() {
  const posts = await prisma.post.findMany({
    where: { author: { email: 'bbcparfait@example.com' }, published: true },
    orderBy: { createdAt: 'desc' },
  });

  const postCount = await prisma.post.count({ where: { published: true } });

  return (
    <main>
      <div className='max-w-[1200px] mx-auto py-10 px-4'>
        <h1 className='text-4xl font-semibold mb-4'>
          Latest posts ({postCount})
        </h1>
        {posts.length ? (
          <ul>
            {posts.map((post) => (
              <li key={post.id} className='mb-2'>
                <Link href={`/posts/${post.slug}`}>
                  {post.title} |{' '}
                  <span className='font-semibold'>
                    {DateTime.fromISO(
                      post.createdAt.toISOString()
                    ).toRelative()}
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        ) : (
          <p>There are no posts.</p>
        )}
      </div>
    </main>
  );
}
